# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skosxl', '0006_auto_20171019_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skosxl.Concept')),
                ('startYear', models.DecimalField(blank=True, decimal_places=2, help_text='Start year, using scaling factor from timeframe specified in the EraScheme', max_digits=10, null=True)),
                ('startYearUncert', models.DecimalField(blank=True, decimal_places=2, help_text='Numerical measure of uncertainty for Start year, using timeframe specified in the EraScheme', max_digits=10, null=True)),
                ('startDate', models.DateField(blank=True, help_text='Use this only if a precise date is known and important (year will be auto-calculated)', null=True)),
                ('endYear', models.DecimalField(blank=True, decimal_places=2, help_text='Start year, using timeframe specified in the EraScheme', max_digits=10, null=True)),
                ('endYearUncert', models.DecimalField(blank=True, decimal_places=2, help_text='Numerical measure of uncertainty for Start year, using timeframe specified in the EraScheme', max_digits=10, null=True)),
                ('endDate', models.DateField(blank=True, help_text='Use this only if a precise date is known and important (year will be auto-calculated)', null=True)),
                ('nextEra', models.OneToOneField(blank=True, help_text='Next Era in sequence - should be at same level of detail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='eras.Era')),
                ('previousEra', models.OneToOneField(blank=True, help_text='Previous Era in sequence - should be at same level of detail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='eras.Era')),
            ],
            bases=('skosxl.concept',),
        ),
        migrations.CreateModel(
            name='EraFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uri', models.URLField(help_text='URI identifying the time frame')),
                ('name', models.CharField(help_text='Display name for the temporal axis, e.g. "millions of years BC"', max_length=100)),
                ('yearFactor', models.FloatField(help_text='How many years represented by a unit in the start/endYear field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EraScheme',
            fields=[
                ('scheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skosxl.Scheme')),
                ('startYear', models.DecimalField(blank=True, decimal_places=2, help_text='Start year, using scaling factor from timeframe specified in the EraScheme', max_digits=10, null=True)),
                ('endYear', models.DecimalField(blank=True, decimal_places=2, help_text='Start year, using timeframe specified in the EraScheme', max_digits=10, null=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eras.EraFrame')),
            ],
            bases=('skosxl.scheme',),
        ),
    ]
